name: Ruff Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install the code linting and formatting tool Ruff
      run: pipx install ruff
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py39
      continue-on-error: true
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py39
      continue-on-error: true
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style: style fixes by ruff'
